print("\n")
print("****************************************************")
print("|---------------------- PONG ----------------------|")
print("|                                                  |")
print("|  By SHERIFF OLAOYE                               |")
print("|                                                  |")
print("|  Email : sheriffolaoye@gmail.com                 |")
print("|  Github: github.com/sheriffolaoye                |")
print("|                                                  |")    
print("****************************************************")